version: '3.8'
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      api-dev:

  mysql:
    container_name: pebdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'pebdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      api-dev:

volumes:
  mysql:
networks:
  api-dev:
